
- name: install packages
  apt: 
    pkg: default-jdk-headless

- name: check django project
  stat:
    path: '{{ project_home }}'
  register: ph

- name: create project
  git:
    repo: https://github.com/opendatakit/xlsform-online.git
    dest: '{{ source_home }}'
    force: yes
    recursive: yes
    update: yes

- name: install python dependencies
  command: '{{ virtualenv_home }}/bin/pip install -r {{ source_home }}/requirements.txt'

- name: template gunicorn
  template: 
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service

- name: template xlsform
  template: 
    src: xlsform.j2
    dest: '/etc/nginx/sites-available/{{ site_name }}'

- name: create nginx link
  file:
    src: '/etc/nginx/sites-available/{{ site_name }}'
    dest: '/etc/nginx/sites-enabled/{{ site_name }}'
    state: link

- name: create env file
  file:
    path: '{{ django_env }}'
    state: touch

- name: set env vars
  lineinfile:
      path: '{{ django_env }}'
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
  with_items:
    - { regexp: '^DJANGO_SECRET_KEY', line: 'DJANGO_SECRET_KEY={{ django_secret_key }}' }
    - { regexp: '^DJANGO_TMP_HOME', line: 'DJANGO_TMP_HOME={{ django_tmp_home }}' }
  no_log: true

- name: configure settings.py
  replace:
    dest: '{{ project_home }}/settings.py'
    regexp: '^ALLOWED_HOSTS = .*'
    replace: "ALLOWED_HOSTS = ['{{ inventory_hostname }}']"

- name: fix permissions
  file:
    path: '{{ site_home }}'
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: run migrations
  shell: 'export $(cat {{ django_env }} | xargs) && {{ virtualenv_home }}/bin/python {{ source_home }}/manage.py migrate'

- name: run collectstatic
  shell: 'export $(cat {{ django_env }} | xargs) && {{ virtualenv_home }}/bin/python {{ source_home }}/manage.py collectstatic --noinput'

- name: enable and restart gunicorn
  systemd:
    name: gunicorn
    enabled: yes
    daemon_reload: yes
    state: restarted

- name: enable and restart nginx
  service: 
    name: nginx 
    enabled: yes
    state: restarted 
